project:
  type: website
  output-dir: docs
  
website:
  title: "COGS 137"
  image: images/background.png
  page-footer:
      left: "This page is built with [Quarto](https://quarto.org/)."
      background: "#92A86A"
      right:
      - text: "License"
        href: LICENSE.md
        
  navbar:
    background: "#92A86A"
    logo: "images/cogs137-logo-hex.png"
    
    right:
      - icon: github
        href: https://github.com/COGS137
        aria-label: GitHub
      - icon: cloud-fill
        href: https://datahub.ucsd.edu/
        aria-label: Datahub
      
    left:
      - text: "Home"
        href: index.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Policies"
        href: policies.qmd
    

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Lecture Slides"
        contents:
          - text: "00-welcome"
            href: content/lectures/00-welcome-slides.html
          - text: "01-intro-to-r"
            href: content/lectures/01-intro-to-r-slides.html
          - text: "02-dplyr"
            href: content/lectures/02-dplyr-slides.html
          - text: "03-tidyr"
            href: content/lectures/03-tidyr-slides.html
          - text: "04-ggplot2"
            href: content/lectures/04-ggplot2-slides.html
          - text: "05-viz"
            href: content/lectures/05-viz-slides.html
      - section: "Lecture Notes"
        contents:
          - text: "00-welcome"
            href: content/lectures/00-welcome.qmd
          - text: "01-intro-to-r"
            href: content/lectures/01-intro-to-r.qmd
          - text: "02-dplyr"
            href: content/lectures/02-dplyr.qmd
          - text: "03-tidyr"
            href: content/lectures/03-tidyr.qmd
          - text: "04-ggplot2"
            href: content/lectures/04-ggplot2.qmd
          - text: "05-viz"
            href: content/lectures/05-viz.qmd
      - section: "Labs"
        contents:
          - text: "Lab01: Tooling and R"
            href: content/labs/01-lab-intro-r.qmd
          - text: "Lab02: Wrangling"
            href: content/labs/02-lab-wrangling.qmd
          - text: "Lab03: Data Viz"
            href: content/labs/03-lab-viz.qmd
      - section: "Lab Slides"
        contents:
          - text: "Lab01"
            href: content/labslides/01-lab-deck.qmd
          - text: "Lab02"
            href: content/labslides/02-lab-deck.qmd
          - text: "Lab03"
            href: content/labslides/03-lab-deck.qmd
      - section: "Lab Answers"
        contents:
          - text: "Lab02: Wrangling (Ans)"
            href: content/lab-ans/lab02-wrangling-ans.qmd
      - section: "Homework"
        contents:
          - text: "HW01"
            href: content/hw/hw-01.qmd
          - text: "HW02"
            href: content/hw/hw-02.qmd
format:
  html:
    theme: material
    css: styles.css
    toc: true

editor: visual

