project:
  type: website
  output-dir: docs
  
website:
  title: "COGS 137"
  image: images/background.png
  page-footer:
      left: "This page is built with [Quarto](https://quarto.org/)."
      background: "#92A86A"
      right:
      - text: "License"
        href: LICENSE.md
        
  navbar:
    background: "#92A86A"
    logo: "images/cogs137-logo-hex.png"
    
    right:
      - icon: github
        href: https://github.com/COGS137
        aria-label: GitHub
      - icon: cloud-fill
        href: https://datahub.ucsd.edu/
        aria-label: Datahub
      
    left:
      - text: "Home"
        href: index.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Policies"
        href: policies.qmd
    

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Lectures"
        contents:
          - text: "00-welcome (notes)"
            href: content/lectures/00-welcome.qmd
          - text: "00-welcome (slides)"
            href: content/lectures/00-welcome-slides.html
          # - text: "01-intro-to-r (notes)"
          #   href: content/lectures/01-intro-to-r.qmd
          # - text: "01-intro-to-r (slides)"
          #   href: content/lectures/01-intro-to-r-slides.html
      - section: "Labs"
        contents:
          # - text: "Lab01: Tooling and R"
          #   href: content/labs/01-lab-intro-r.qmd
      - section: "Lab Slides"
        contents:
          # - text: "Lab01"
          #   href: content/labslides/01-lab-deck.qmd
      - section: "Assignments"

format:
  html:
    theme: material
    css: styles.css
    toc: true

editor: visual

