baseurl = "https://cogs137.github.io/website"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "COGS 137"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Shannon Ellis"
  bio = ""
  job = "Assistant Teaching Professor"
  location = "UC San Diego"
  gravatarEmail = "sellis@ucsd.edu"
  # Your profile picture
  #  picture = ""
  twitter = "Shannon_E_Ellis"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "schedule"
  name = "Schedule"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 4
  identifier = "datahub"
  name = "Datahub"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://datahub.ucsd.edu/"
[[menu.main]]
  weight = 5
  identifier = "github"
  name = "GitHub"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://github.com/COGS137"


[[menu.footer]]
  weight = 1
  identifier = "UCSD"
  name = "UCSD CogSci"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "https://cogsci.ucsd.edu/"
[[menu.footer]]
  weight = 2
  name = "Datahub"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://datahub.ucsd.edu/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/COGS137/"
[[menu.footer]]


[params]
  dateFormat = "Septebmer 23, 2021"
  background = "img/background.jpg"
  favicon = "img/favicon.ico"


[[redirects]]
	from = "/*"
	to = "/404/index.html"
	status = 404