---
title: "CS03: Final Report"
date: "Due: Dec 3 (11:59 PM)"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    toc_float: true
    fig_caption: true
---

At this point you have a sense for what these case studies are all about, as you and your group pull together your third full data science report. This report will again include your analysis from top (the background and question) to bottom (your analysis, interpretation, and conclusions). You will be asked to answer the questions provided in class, using the data provided; however, you will also need to extend the case study beyond what was presented in class.

We'll be grading to see that you have:
1. all necessary code for each section of the project with necessary code comments.
2. explanatory text that guides the reader from start to finish.
3. polished visualizations that allow the reader to both understand the data you're working with and your conclusions.
4. complete analyses to answer the questions of interest presented in your report.

This will be submitted and graded as a group. **One submission per group.**

## Getting started

Here are the steps for getting started:

- This will be completed in cs03 group repository that has been created for you and your group mates.
- Make any changes needed as outlined by the tasks you need to complete for the assignment
- Periodically commit changes (for example, once per each new part)
- Knit your final report to HTML.
- Push all your changes back to your GitHub repo
- This case study will be graded from GitHub.

Your final GitHub push prior to the deadline will be used for grading.

### Imports

You are allowed to import whichever packages you like for this case study report.

## Case Study Report

Your case study can be organized however you see best fit, but we'll be looking for the following general sections:

- Title
- Authors
- Background/Introduction
- Question(s)
- Data 
- Data Import
- Data Wrangling
- Exploratory Data Analysis
- Data Analysis
- Results
- Discussion of results
- Conclusion

Now, you may want to combine some of these sections (i.e. include your results and discussion among your analysis code). That's *totally* allowed, but we'll be looking to see that your report includes sufficient information to understand what you did, why you did it, and what your results are.

### Extending the Analysis

In addition to getting the code presented in class working, adding explanatory text to your report, and generating polished visualizations, you and your group must "extend the analysis" presented in class in a meaningful way. Now "meaningful" is not a very-easily-measured term. A meaningful extension could be carrying out analysis to answer an additional sub-question beyond what was presented in class, or including a really extensive exploratory data analysis, or generating a really superb set of visualizations to convey your groups' results. To determine whether your extension is "meaningful," you and your group should be able to answer "yes" to the question "Does our extension add something important to this report beyond what was presented in class?" 

