---
title: "HW 04 - CS02 Data Wrangling"
date: "Due: Nov 15 (11:59 PM)"
output: 
  html_document: 
    css: hw.css
    theme: yeti
    toc: true
    toc_float: true
    fig_caption: true
---

This assignment is meant to get you on the right track with your first case study. While ultimately your work here will benefit your group, this will be **completed individually**. You will submit your work using the hw04 GitHub classroom template (link on Canvas).

The idea here is that there are *a lot* of datasets to wrangle for Case Study 02. Each group member will be responsible for writing the comments/description *and* getting the code to execute for a subset of the Case Study 02 datasets. This way, when you get together to combine forces (and the datasets), you will be able to hit the ground running. Each submission should have *code and explanations* for the wrangling that they've done.

We'll be checking to see that you:
1. have code that wrangles a subset of the datasets.
2. have accompanying text that describes what is going on in the code.
3. have comments in your code as needed.

## Getting started

Here are the steps for getting started:

- To get started, accept the hw04 assignment (link on Canvas), clone the repo (using SSH) into RStudio on datahub. Update the author name at the top of the .Rmd file in the YAML to be your name. And, then you're ready to go! Be sure to knit when you're finished. This assignment will be graded from GitHub. **You should NOT submit to Gradescope.**

Your final GitHub push prior to the deadline will be used for grading.

### Imports

Use the notes from class to determine what packages you need to import to accomplish the tasks below. You are allowed to import whichever packages you like for this case study report.

### The Data 

The data you'll be using are the data we've been using in class when discussing the first case study: Disparities in Youth Connection. 

## Part I: Dataset Selection

Discuss with your group mates to determine who is going to wrangle which datasets. To help guide you in this process, a reasonable breakdown of effort for a group of 3 would be:

- Student 1: Demographic & Population Data 
- Student 2: State FIPS codes, Police Staffing, & Unemployment 
- Student 3: Poverty, Violent Crime & Right to Carry

Specify which datasets you are going to wrangle in this section.


## Part II: Data Import

In this section, you'll need to import the case study data into your GitHub repository.

## Part III: Data Wrangling

In this section, you'll need to wrangle the data into tidy tibbles/dataframes. Use the code presented in class to guide you. But, you'll need to add explanations and code comments to guide the viewer as to what each bit of code/step in the process does.

## Submission

Be sure to knit your file to HTML and push your changes to GitHub.




