---
title: "Lab 07: Logistic Regression"
author: ""
format:
  revealjs:
    embed-resources: true
    slide-number: true
    chalkboard: false 
    preview-links: auto
    logo: img/cogs137-logo-hex.png
    footer: <https://cogs137.github.io/website/>
    execute:
      echo: true
---

# Lab 07: Logistic Regression {background-color="#0E3A53"}

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
```

## Agenda

1.  Lab 07: Modelling resumes
2.  Getting started with lab

## Data come from...

"Are Emily and Greg More Employable than Lakisha and Jamal? A Field Experiment on Labor Market Discrimination."

Bertrand, Marianne, and Sendhil Mullainathan. 2003. <https://doi.org/10.3386/w9873>.

## Study

Goal: understand the influence of race and gender on job application callback rates

. . .

#### Specs:

-   Two cities: Boston and Chicago
-   Time: several months in 2001 and 2002

. . .

#### Plan:

1.  Researchers generated resumes, randomizing years of experience and education details
2.  Then: randomly assigned a name to the resume that would communicate the applicant's gender and race

-   they tested these names and removed those that did not suggest gender and race consistently
-   i.e. Lakisha was a name that their survey indicated would be interpreted as a black woman, while Greg was a name that would generally be interpreted to be associated with a white male."

## Backwards elimination (Logistic Regression)

-   Start with **full** model (including all candidate explanatory variables and all candidate interactions)

-   Remove one variable at a time, and select the model with the *lowest* AIC

-   Continue until AIC does not decrease

. . .

-   You do NOT have to include every model in your lab...just the final one you settle on.

## A note on this lab

-   There are three parts. We'll be grading to see that you've done *some* EDA and have fit and interpreted at least two models (single and multiple predictors model)
-   It's OK if you don't get to backwards elimination
