---
title: "Lab 06 - Exploring Case Study 01"
date: "2023-11-17"
output: 
  html: 
    highlight: pygments
    css: lab.css
    preview-links: auto
    execute:
      eval: false
---

## Introduction

This week in class we've been discussing data related to [Biomarkers of Recent Cannabis Use in Blood, Oral Fluid and Breath](https://academic.oup.com/jat/article/45/8/820/6311388). You've *seen* the data in class, but you may not have had a chance to really work with the data yourself yet. This lab will allow you to get more comfortable with the data ahead of the associated case study report coming due. While the case study report will be submitted in groups, this will be submitted individually.The idea is that while you are still encouraged to work together during lab, you and your groupmates may come up with separate ideas. This will allow you to have more ideas when you get together and start working on the case study together.

# Getting started

To get started, accept the lab06 assignment (link on Canvas), clone the repo (using SSH) into RStudio on datahub. Update the author name at the top of the .Rmd file in the YAML to be your name. And, then you're ready to go!

# Packages

In this lab we will work with the `tidyverse` package. Be sure to load that in before continuing with the lab. You are allowed to load in additional packages for this lab if needed.

# The data

In this lab you will first read in the data, which has been provided to you in three RData files in the `data` folder: `compounds.RData` (lists of compounds for each matrix), `timepoints.RData` (timepoints for each matrix), and `data_clean.RData` (wrangled data for each matrix).

Note that these data have already been wrangled for you (as demonstrated in class). For your case study, you will have to go through the wrangling steps to get you to this point but for this lab, you will just start with the already-wrangled data.

# Exercises

## Part 1: Exploratory Data Analysis (EDA)

Create at least two (2) visualizations that help you learn more about these data beyond what was presented in class. (This is intentionally vague. We want you to look at the data and figure out what would be most helpful to visualize from the provided data. These could be different variables than what we looked at in class. Data could be faceted. Something totally different!) These do *not* have to be fully polished visualizations, but it should be clear from the visualization and accompanying text what's to be learned from the visualization.

## Part 2: Possible extensions?

Think about the data you have access to, the EDA/analysis presented in class, and the questions we said we're going to address. What *possible* extensions to this analysis would you be interested in carrying out? This is a space for brainstorming. Include any possible thoughts you have here, even if they aren't "good" or you aren't sure if they are "possible." This can be used as a jumping off point for when you start discussing analysis extensions with your group.
