---
title: "Lab 05 - Exploring Case Study 01"
date: "2021-10-29"
output: 
  tufte::tufte_html:
    tufte_variant: "envisioned"
    highlight: pygments
    css: lab.css
link-citations: yes
---

```{r include=FALSE}
library(tidyverse)
library(tufte)
library(knitr)
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  digits = 2
  )
knitr::opts_chunk$set(eval = FALSE)
```


## Introduction

This week in class we've been discussing data related to youth disconnection. You've *seen* the data in class, but you may not have had a chance to really work with the data yourself yet. This lab will allow you to get more comfortable with the data ahead of the associated homework and case study report coming due. While hw03 and the case study report will be submitted in groups, this will be submitted individually. The idea is that while you are still encouraged to work together during lab, you and your groupmates may come up with separate ideas. This will allow you to have more ideas when you get together and start brainstorming!

# Getting started

To get started, accept the lab05 assignment (link on Canvas), clone the repo (using SSH) into RStudio on datahub. Update the author name at the top of the .Rmd file in the YAML to be your name. And, then you're ready to go!

# Packages

In this lab we will work with the `tidyverse` package. Be sure to load that in before continuing with the lab. You are allowed to load in additional packages for this lab if needed.


# The data

In this lab you will first read in the data ('wrangled_major_groups_data.csv', 'wrangled_latinx_subgroups_data.csv', and 'wrangled_asian_subgroups_data.csv') from the `data/` folder (provided in the template). Note that these data have already been wrangled for you. For your case study, you will have to go through the wrangling steps to get you to this point.


# Exercises

## Part 1: Exploratory Data Analysis (EDA)

1.  Create at least two (2) visualizations that start to explore the information provided in this dataset. (This is intentionally vague. We want you to look at the data and figure out what would be most helpful to visualize from the provided data.) These do not have to be fully polished visualizations, but it should be clear what each is displaying and you should have some text describing what the visualization tells the user in your lab.


## Part 2: Wrangling Code

Two very similar functions were provided during the [CS 01 Data lecture](https://cogs137.github.io/website/lecslides/10-cs1-data.html) on `clean_table()` on slide 55 and `clean_table_2018()` on slide 65.

2. First, describe what each function does.

3. Then, explain why two different functions were needed.

4. And finally, brainstorm whether or not there's any way that you could use a single function instead of two very similar functions. You *could* write this "improved" function *or* just describe your thoughts.


## Part 3: Possible extensions? 

5.  Think about the data you have access to, the EDA/analysis presented in class, and the questions we said we're going to address. What *possible* extensions to this analysis would you be interested in carrying out? This is a space for brainstorming. Include any possible thoughts you have here, even if they aren't "good" or you aren't sure if they are "possible." This can be used as a jumping off point for when you start discussing analysis extensions with your group.
